services:
  ersa:
    init: true
    privileged: true
    build: .
    user: "5087"
    ports:
      - "6666:6666"
    volumes:
      - /home/Felix.Grzelka/.cache/huggingface/datasets:/home/Felix.Grzelka/.cache/huggingface/datasets
      - /tmp/ersa-docker:/tmp/ersa
      - "../remotefs:/remotefs"
      - ".:/app"
      - /tmp/ersa-docker/.pyenv/versions:/home/felix/.pyenv/versions
      - /home/Felix.Grzelka/ersa/data:/home/Felix.Grzelka/ersa/data
    environment:
      HOME: /home/felix
      WORKINGDIR: /home/felix/projects/uni/phd/kisz/ersa
    working_dir: /app
    # attach one gpu to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]