services:
  megaclite:
    privileged: true
    build: .
    user: "5087"
    ports:
      - "6666:6666"
    volumes:
      - /tmp/megaclite-docker:/tmp/megaclite
      - "../remotefs:/remotefs"
      - ".:/app"
      - /tmp/megaclite-docker/.pyenv/versions:/home/felix/.pyenv/versions
    environment:
      HOME: /home/felix
      WORKINGDIR: /home/felix/projects/uni/phd/kisz/megaclite
    working_dir: /app
    # attach one gpu to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]